--- # moj pierwszy playbook


- name: linux
  hosts: AGH_Ilski
  tasks:
  - name: robimy ping na AGH
    action: ping

- name: winows
  hosts: WINSRV_Ilski_P
  tasks:
  - name: robimy ping na windows
    action: win_ping
