--- # moj pierwszy playbook

- hosts: AGH_Ilski
  tasks:
  - name: robimy ping na AGH
    action: ping

- hosts: WINSRV_Ilski_P
  gather_facts: false
  tasks:
  - name: robimy ping na WINSRV
    action: win_ping
