--- # moj pierwszy playbook

- hosts: AGH_Ilski
  tasks:
  - name: robimy ping na AGH
    action: ping

- name: Test connectivity with Windows hosts over SSH
  hosts: WINSRV_Ilski_P
  gather_facts: no
  tasks:
  - name: Ping Windows host
      win_ping:
